### ISSUE TITLE
UX allow replacing "gender/race" icon with discord avatar or custom avatar

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#19]
dk — Today at 3:48 PM
when can we upload our own character art

**Comment by Elite747** [comment]
Not sure if I want to do this. The purpose of those icons is to clearly show to raid leaders who is what for planning out your teams. Uploads would have to be moderated to make sure they are not vulgar and actually depict the character in some form.

**Comment by Bonkeybee** [comment]
I agree with you on this. Though the same argument for moderation can be
applied to the raid leaders avatars too. I also really like the new class
race role icon combo and would rather keep that.

**Comment by Elite747** [comment]
> Though the same argument for moderation can be applied to the raid leaders avatars too.

Discord doesn't allow adult content in avatars in their [guidelines](https://discord.com/guidelines). The moderation is already done for us.
