### ISSUE TITLE
UX sometimes when editing loot list the tooltip icon covers the mouse and bugs out

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#33]
![image](https://user-images.githubusercontent.com/9619823/113221824-646d0180-924b-11eb-9497-d39149485e7a.png)

**Comment by Bonkeybee** [comment]
Will close this as wontfix

**Comment by Bonkeybee** [comment]
Another instance of the wowhead tooltip bugging out:

Sylsa — Today at 5:35 PM
So I dont know if this is a bug due to monitor size (im doing this on my 2nd monitor which is a 27inch 1920x1080) but picking only these shoulders as an offspec item glitched out and once you click you cant click on others things until you click on another add item or drag the window around https://gyazo.com/9057d263850e58b92d216e4c6dcfcad7

**Comment by Elite747** [comment]
Submitted this issue to Wowhead as it's a bug on their website as well. Not much more I can do on my end without completely writing a custom tooltip. This may be what https://seventyupgrades.com/ does, but that's way more work than it's worth given the scope of this program.

Commit 93d68ce562ce7e7bfdb3c31bdbdc48db3951f45c should have fixed Sylsa's particular issue.
