### ISSUE TITLE
Show more information for each character on the characters screen

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#46]
![image](https://user-images.githubusercontent.com/9619823/115104921-817b2300-9f21-11eb-8310-b4ae5202d4f9.png)
Perhaps showing information like what team that character has applied to or what team they are a part of would be useful.
Also, if displaying this information it would be easier to read if the rows background color alternated slightly.

**Comment by Elite747** [comment]
Added team names in commit e310c476ae5cc52f9fe31a6eca2da3c010295022.
