### ISSUE TITLE
Duplicates of rings/trinkets needs to be allowed if they are not unique (but perhaps show a warning)

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#61]
This would be in the future but is there a way to allow doubles of items onto the loot list? In P3 my BiS is 2 of the same ring. Right now when you have an item on your list you can’t select it again.

**Comment by Elite747** [comment]
There's 4 rings, no trinkets, and a handful of weapons that are non-unique and could possibly be obtained multiple times.

The rings are:
https://tbc.wowhead.com/item=35733/ring-of-harmonic-beauty (SP)
https://tbc.wowhead.com/item=32528/blessed-band-of-karabor (BT)
https://tbc.wowhead.com/item=32527/ring-of-ancient-knowledge (BT)
https://tbc.wowhead.com/item=32526/band-of-devastation (BT)

and the weapons are:
https://tbc.wowhead.com/item=34165/fang-of-kalecgos (SP)
https://tbc.wowhead.com/item=34214/muramasa (SP)
https://tbc.wowhead.com/item=32269/messenger-of-fate (BT)
https://tbc.wowhead.com/item=32943/swiftsteel-bludgeon (BT)
https://tbc.wowhead.com/item=32254/the-brutalizer (BT)
https://tbc.wowhead.com/item=32262/syphon-of-the-nathrezim (BT)
https://tbc.wowhead.com/item=32369/blade-of-savagery (BT)
https://tbc.wowhead.com/item=30874/the-unbreakable-will (HS)
https://tbc.wowhead.com/item=30881/blade-of-infamy (HS)
https://tbc.wowhead.com/item=29924/netherbane (TK)

Interesting note about the weapons is some or all of them may be main-hand-only until a later phase. Those will need some more looking into.

The first item that may run into this is Netherbane out of Tempest Keep, so we've got a bit of time to get this implemented.
