### ISSUE TITLE
Add a role count (tank/heal/dps), total player count, and possibly a class count to the raid team page

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#70]
Quigle🐈 — Today at 11:28 AM
Filling out the Gjalla roster, I find myself counting members (to audit I've slotted in the right people/classes). I'd love the app to display a count and/or a summary by class and/or spec.    mmmmmaybe on the 'all teams' page, but anywhere is fine.

**Comment by Elite747** [comment]
Total player counts was introduced in commit 8e93653. Role/class counts are also available via the charts.
