### ISSUE TITLE
Role checks such as Loot Master should occur before clicking "finish"

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#81]
Example: creating a raid on the team page only checks for the appropriate role at the end when the user clicks finish. The check should occur before even opening the wizard to create a raid.

**Comment by Elite747** [comment]
This was not an issue with showing or hiding the button, but rather the authorization tokens were still reading old claims. This won't be an issue in production, but dd63fe6 removes these old claims which fixes this issue for dev environments.
