### ISSUE TITLE
Add links to a user's other characters when viewing their page

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#87]
It would be useful to quickly be able to view linked characters (ones that were all created and verified under the same discord account)

![image](https://user-images.githubusercontent.com/9619823/118274238-7f59a500-b48a-11eb-9c61-72f93842f214.png)

**Comment by Elite747** [comment]
Added with 2c1e9c082440275f76726e108218769aa06cdc0b
