### ISSUE TITLE
Add ability to toggle "always pass" to player's loot lists

### ISSUE THREAD

**Issue by Bonkeybee** [Elite747/ValhallaLootList#95]
Looting is slowed down a lot because master looters have to ask each person if they want an item even if they no longer need it. Each week these same players "pass" on the same item and wastes time. An option to toggle an item's "passing status" that players can use from their locked and submitted list would help loot masters distribute loot faster.

**Comment by Elite747** [comment]
Added in commit e6380d835e7a662b24303d2955ba96aef553b1a7.
